# Content Filtering

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
df = pd.DataFrame([
    {'title': 'A', 'genre': 'Pop', 'label': 'PT. A'},
    {'title': 'B', 'genre': 'Keroncong', 'label': 'PT. A'},
    {'title': 'C', 'genre': 'Dangdut', 'label': 'PT. A'},
    {'title': 'D', 'genre': 'Pop', 'label': 'PT. B'},
    {'title': 'E', 'genre': 'Keroncong', 'label': 'PT. B'},
    {'title': 'F', 'genre': 'Dangdut', 'label': 'PT. B'},
    {'title': 'G', 'genre': 'Pop', 'label': 'PT. C'},
    {'title': 'H', 'genre': 'Keroncong', 'label': 'PT. C'},
    {'title': 'I', 'genre': 'Dangdut', 'label': 'PT. C'},
    {'title': 'J', 'genre': 'Pop', 'label': 'PT. C'}])
df

  title      genre  label
0     A        Pop  PT. A
1     B  Keroncong  PT. A
2     C    Dangdut  PT. A
3     D        Pop  PT. B
4     E  Keroncong  PT. B
5     F    Dangdut  PT. B
6     G        Pop  PT. C
7     H  Keroncong  PT. C
8     I    Dangdut  PT. C
9     J        Pop  PT. C

In [4]:
ecv = CountVectorizer()
mgenre = ecv.fit_transform(df['genre'])
ecv.get_feature_names()

['dangdut', 'keroncong', 'pop']

In [5]:
mgenre

<10x3 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [6]:
mgenre.toarray()

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [7]:
cosScore = cosine_similarity(mgenre)
cosScore

array([[1., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0., 1.]])

In [8]:
cosScore.shape

(10, 10)

In [9]:
produk_mirip = list(enumerate(cosScore[7]))
produk_mirip = sorted(produk_mirip, key=lambda x: x[1], reverse=True)
produk_mirip

[(1, 1.0),
 (4, 1.0),
 (7, 1.0),
 (0, 0.0),
 (2, 0.0),
 (3, 0.0),
 (5, 0.0),
 (6, 0.0),
 (8, 0.0),
 (9, 0.0)]

In [10]:
for i in produk_mirip[:5]:
    print(df.iloc[i[0]])

title            B
genre    Keroncong
label        PT. A
Name: 1, dtype: object
title            E
genre    Keroncong
label        PT. B
Name: 4, dtype: object
title            H
genre    Keroncong
label        PT. C
Name: 7, dtype: object
title        A
genre      Pop
label    PT. A
Name: 0, dtype: object
title          C
genre    Dangdut
label      PT. A
Name: 2, dtype: object

In [11]:
df2 = pd.read_csv('~/Downloads/anime.csv')
df2 = df2.iloc[0:850]
df2.head(20)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
5,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,"Comedy, Drama, School, Shounen, Sports",TV,10,9.15,93351
6,11061,Hunter x Hunter (2011),"Action, Adventure, Shounen, Super Power",TV,148,9.13,425855
7,820,Ginga Eiyuu Densetsu,"Drama, Military, Sci-Fi, Space",OVA,110,9.11,80679
8,15335,Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",Movie,1,9.10,72534
9,15417,Gintama&#039;: Enchousen,"Action, Comedy, Historical, Parody, Samurai, S...",TV,13,9.11,81109
10,4181,Clannad: After Story,"Drama, Fantasy, Romance, Slice of Life, Supern...",TV,24,9.06,456749
11,28851,Koe no Katachi,"Drama, School, Shounen",Movie,1,9.05,102733
12,918,Gintama,"Action, Comedy, Historical, Parody, Samurai, S...",TV,201,9.04,336376
13,2904,Code Geass: Hangyaku no Lelouch R2,"Action, Drama, Mecha, Military, Sci-Fi, Super ...",TV,25,8.98,572888
14,28891,Haikyuu!! Second Season,"Comedy, Drama, School, Shounen, Sports",TV,25,8.93,179342
15,199,Sen to Chihiro no Kamikakushi,"Adventure, Drama, Supernatural",Movie,1,8.93,466254
16,23273,Shigatsu wa Kimi no Uso,"Drama, Music, Romance, School, Shounen",TV,22,8.92,416397
17,24701,Mushishi Zoku Shou 2nd Season,"Adventure, Fantasy, Historical, Mystery, Seine...",TV,10,8.88,75894
18,12355,Ookami Kodomo no Ame to Yuki,"Fantasy, Slice of Life",Movie,1,8.84,226193
19,1575,Code Geass: Hangyaku no Lelouch,"Action, Mecha, Military, School, Sci-Fi, Super...",TV,25,8.83,715151

In [12]:
len(df2['name'])

850

In [13]:
df2.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [14]:
ext = CountVectorizer(tokenizer = lambda x: x.split(', '))
mgenre = ext.fit_transform(df2['genre'])
print(len(ext.get_feature_names()))
print(ext.get_feature_names())

40
['action', 'adventure', 'cars', 'comedy', 'dementia', 'demons', 'drama', 'ecchi', 'fantasy', 'game', 'harem', 'historical', 'horror', 'josei', 'kids', 'magic', 'martial arts', 'mecha', 'military', 'music', 'mystery', 'parody', 'police', 'psychological', 'romance', 'samurai', 'school', 'sci-fi', 'seinen', 'shoujo', 'shoujo ai', 'shounen', 'shounen ai', 'slice of life', 'space', 'sports', 'super power', 'supernatural', 'thriller', 'vampire']

In [15]:
mgenre

<850x40 sparse matrix of type '<class 'numpy.int64'>'
	with 3696 stored elements in Compressed Sparse Row format>

In [16]:
mgenre.toarray()

array([[0, 0, 0, ..., 1, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [17]:
cs = cosine_similarity(mgenre)

In [18]:
animesuka = 'Hunter x Hunter (2011)'
indexsuka = df2[df2['name'] == animesuka].index[0]
indexsuka

6

In [19]:
animesama = list(enumerate(cs[indexsuka]))

In [20]:
animesamasortir = sorted(animesama, key = lambda x:x[1], reverse = True)
animesamasortir

[(6, 1.0),
 (112, 1.0),
 (145, 1.0),
 (146, 1.0),
 (202, 1.0),
 (784, 0.8944271909999159),
 (398, 0.8660254037844388),
 (698, 0.8660254037844388),
 (182, 0.8164965809277261),
 (271, 0.8164965809277261),
 (352, 0.8164965809277261),
 (753, 0.8164965809277261),
 (74, 0.7559289460184544),
 (206, 0.7559289460184544),
 (231, 0.7559289460184544),
 (241, 0.7559289460184544),
 (515, 0.7559289460184544),
 (566, 0.7559289460184544),
 (588, 0.7559289460184544),
 (644, 0.7559289460184544),
 (113, 0.75),
 (175, 0.75),
 (304, 0.75),
 (339, 0.75),
 (371, 0.75),
 (513, 0.75),
 (561, 0.75),
 (579, 0.75),
 (629, 0.75),
 (821, 0.75),
 (680, 0.7071067811865475),
 (64, 0.6708203932499369),
 (86, 0.6708203932499369),
 (95, 0.6708203932499369),
 (101, 0.6708203932499369),
 (178, 0.6708203932499369),
 (257, 0.6708203932499369),
 (268, 0.6708203932499369),
 (290, 0.6708203932499369),
 (461, 0.6708203932499369),
 (486, 0.6708203932499369),
 (526, 0.6708203932499369),
 (582, 0.6708203932499369),
 (615, 0.6708203932499369),
 (695, 0.6708203932499369),
 (717, 0.6708203932499369),
 (719, 0.6708203932499369),
 (769, 0.6708203932499369),
 (795, 0.6708203932499369),
 (841, 0.6708203932499369),
 (76, 0.6123724356957946),
 (104, 0.6123724356957946),
 (133, 0.6123724356957946),
 (141, 0.6123724356957946),
 (143, 0.6123724356957946),
 (163, 0.6123724356957946),
 (212, 0.6123724356957946),
 (255, 0.6123724356957946),
 (288, 0.6123724356957946),
 (346, 0.6123724356957946),
 (374, 0.6123724356957946),
 (440, 0.6123724356957946),
 (705, 0.6123724356957946),
 (765, 0.6123724356957946),
 (803, 0.6123724356957946),
 (24, 0.5773502691896258),
 (121, 0.5773502691896258),
 (249, 0.5773502691896258),
 (307, 0.5773502691896258),
 (333, 0.5773502691896258),
 (350, 0.5773502691896258),
 (355, 0.5773502691896258),
 (479, 0.5773502691896258),
 (576, 0.5773502691896258),
 (607, 0.5773502691896258),
 (611, 0.5773502691896258),
 (612, 0.5773502691896258),
 (634, 0.5773502691896258),
 (740, 0.5773502691896258),
 (775, 0.5773502691896258),
 (814, 0.5773502691896258),
 (1, 0.5669467095138407),
 (777, 0.5669467095138407),
 (200, 0.5303300858899106),
 (42, 0.5),
 (136, 0.5),
 (137, 0.5),
 (165, 0.5),
 (173, 0.5),
 (193, 0.5),
 (205, 0.5),
 (227, 0.5),
 (251, 0.5),
 (272, 0.5),
 (281, 0.5),
 (286, 0.5),
 (301, 0.5),
 (332, 0.5),
 (364, 0.5),
 (379, 0.5),
 (381, 0.5),
 (385, 0.5),
 (390, 0.5),
 (400, 0.5),
 (408, 0.5),
 (420, 0.5),
 (430, 0.5),
 (431, 0.5),
 (433, 0.5),
 (472, 0.5),
 (499, 0.5),
 (508, 0.5),
 (521, 0.5),
 (523, 0.5),
 (554, 0.5),
 (555, 0.5),
 (573, 0.5),
 (574, 0.5),
 (581, 0.5),
 (584, 0.5),
 (593, 0.5),
 (594, 0.5),
 (660, 0.5),
 (684, 0.5),
 (690, 0.5),
 (703, 0.5),
 (723, 0.5),
 (752, 0.5),
 (788, 0.5),
 (789, 0.5),
 (798, 0.5),
 (809, 0.5),
 (811, 0.5),
 (815, 0.5),
 (830, 0.5),
 (29, 0.4472135954999579),
 (55, 0.4472135954999579),
 (106, 0.4472135954999579),
 (127, 0.4472135954999579),
 (138, 0.4472135954999579),
 (194, 0.4472135954999579),
 (207, 0.4472135954999579),
 (252, 0.4472135954999579),
 (253, 0.4472135954999579),
 (260, 0.4472135954999579),
 (261, 0.4472135954999579),
 (274, 0.4472135954999579),
 (293, 0.4472135954999579),
 (344, 0.4472135954999579),
 (345, 0.4472135954999579),
 (349, 0.4472135954999579),
 (378, 0.4472135954999579),
 (395, 0.4472135954999579),
 (416, 0.4472135954999579),
 (446, 0.4472135954999579),
 (454, 0.4472135954999579),
 (480, 0.4472135954999579),
 (482, 0.4472135954999579),
 (510, 0.4472135954999579),
 (519, 0.4472135954999579),
 (524, 0.4472135954999579),
 (535, 0.4472135954999579),
 (538, 0.4472135954999579),
 (544, 0.4472135954999579),
 (545, 0.4472135954999579),
 (551, 0.4472135954999579),
 (557, 0.4472135954999579),
 (587, 0.4472135954999579),
 (603, 0.4472135954999579),
 (605, 0.4472135954999579),
 (606, 0.4472135954999579),
 (616, 0.4472135954999579),
 (643, 0.4472135954999579),
 (645, 0.4472135954999579),
 (655, 0.4472135954999579),
 (662, 0.4472135954999579),
 (666, 0.4472135954999579),
 (687, 0.4472135954999579),
 (704, 0.4472135954999579),
 (708, 0.4472135954999579),
 (720, 0.4472135954999579),
 (743, 0.4472135954999579),
 (759, 0.4472135954999579),
 (779, 0.4472135954999579),
 (785, 0.4472135954999579),
 (804, 0.4472135954999579),
 (13, 0.4082482904638631),
 (19, 0.4082482904638631),
 (22, 0.4082482904638631),
 (135, 0.4082482904638631),
 (140, 0.4082482904638631),
 (195, 0.4082482904638631),
 (273, 0.4082482904638631),
 (358, 0.4082482904638631),
 (361, 0.4082482904638631),
 (402, 0.4082482904638631),
 (445, 0.4082482904638631),
 (476, 0.4082482904638631),
 (481, 0.4082482904638631),
 (637, 0.4082482904638631),
 (641, 0.4082482904638631),
 (700, 0.4082482904638631),
 (741, 0.4082482904638631),
 (745, 0.4082482904638631),
 (810, 0.4082482904638631),
 (838, 0.4082482904638631),
 (2, 0.3779644730092272),
 (4, 0.3779644730092272),
 (8, 0.3779644730092272),
 (9, 0.3779644730092272),
 (12, 0.3779644730092272),
 (23, 0.3779644730092272),
 (63, 0.3779644730092272),
 (65, 0.3779644730092272),
 (120, 0.3779644730092272),
 (216, 0.3779644730092272),
 (306, 0.3779644730092272),
 (342, 0.3779644730092272),
 (455, 0.3779644730092272),
 (458, 0.3779644730092272),
 (465, 0.3779644730092272),
 (496, 0.3779644730092272),
 (622, 0.3779644730092272),
 (657, 0.3779644730092272),
 (697, 0.3779644730092272),
 (748, 0.3779644730092272),
 (754, 0.3779644730092272),
 (770, 0.3779644730092272),
 (818, 0.3779644730092272),
 (70, 0.35355339059327373),
 (117, 0.35355339059327373),
 (222, 0.35355339059327373),
 (331, 0.35355339059327373),
 (359, 0.35355339059327373),
 (363, 0.35355339059327373),
 (380, 0.35355339059327373),
 (421, 0.35355339059327373),
 (423, 0.35355339059327373),
 (475, 0.35355339059327373),
 (569, 0.35355339059327373),
 (577, 0.35355339059327373),
 (586, 0.35355339059327373),
 (623, 0.35355339059327373),
 (626, 0.35355339059327373),
 (639, 0.35355339059327373),
 (663, 0.35355339059327373),
 (691, 0.35355339059327373),
 (843, 0.35355339059327373),
 (198, 0.3333333333333333),
 (419, 0.3333333333333333),
 (692, 0.3333333333333333),
 (151, 0.31622776601683794),
 (11, 0.2886751345948129),
 (15, 0.2886751345948129),
 (61, 0.2886751345948129),
 (90, 0.2886751345948129),
 (94, 0.2886751345948129),
 (105, 0.2886751345948129),
 (115, 0.2886751345948129),
 (153, 0.2886751345948129),
 (162, 0.2886751345948129),
 (166, 0.2886751345948129),
 (183, 0.2886751345948129),
 (184, 0.2886751345948129),
 (214, 0.2886751345948129),
 (234, 0.2886751345948129),
 (275, 0.2886751345948129),
 (292, 0.2886751345948129),
 (294, 0.2886751345948129),
 (295, 0.2886751345948129),
 (343, 0.2886751345948129),
 (351, 0.2886751345948129),
 (360, 0.2886751345948129),
 (389, 0.2886751345948129),
 (391, 0.2886751345948129),
 (394, 0.2886751345948129),
 (432, 0.2886751345948129),
 (439, 0.2886751345948129),
 (441, 0.2886751345948129),
 (457, 0.2886751345948129),
 (468, 0.2886751345948129),
 (478, 0.2886751345948129),
 (509, 0.2886751345948129),
 (546, 0.2886751345948129),
 (550, 0.2886751345948129),
 (592, 0.2886751345948129),
 (620, 0.2886751345948129),
 (628, 0.2886751345948129),
 (658, 0.2886751345948129),
 (659, 0.2886751345948129),
 (661, 0.2886751345948129),
 (709, 0.2886751345948129),
 (721, 0.2886751345948129),
 (728, 0.2886751345948129),
 (805, 0.2886751345948129),
 (808, 0.2886751345948129),
 (831, 0.2886751345948129),
 (845, 0.2886751345948129),
 (20, 0.25),
 (32, 0.25),
 (35, 0.25),
 (36, 0.25),
 (37, 0.25),
 (39, 0.25),
 (44, 0.25),
 (51, 0.25),
 (58, 0.25),
 (72, 0.25),
 (78, 0.25),
 (82, 0.25),
 (87, 0.25),
 (98, 0.25),
 (100, 0.25),
 (119, 0.25),
 (122, 0.25),
 (124, 0.25),
 (125, 0.25),
 (132, 0.25),
 (139, 0.25),
 (148, 0.25),
 (170, 0.25),
 (177, 0.25),
 (179, 0.25),
 (185, 0.25),
 (188, 0.25),
 (203, 0.25),
 (221, 0.25),
 (230, 0.25),
 (232, 0.25),
 (237, 0.25),
 (254, 0.25),
 (266, 0.25),
 (279, 0.25),
 (302, 0.25),
 (303, 0.25),
 (305, 0.25),
 (316, 0.25),
 (318, 0.25),
 (324, 0.25),
 (336, 0.25),
 (340, 0.25),
 (353, 0.25),
 (357, 0.25),
 (366, 0.25),
 (367, 0.25),
 (377, 0.25),
 (386, 0.25),
 (399, 0.25),
 (412, 0.25),
 (443, 0.25),
 (447, 0.25),
 (464, 0.25),
 (471, 0.25),
 (474, 0.25),
 (483, 0.25),
 (494, 0.25),
 (495, 0.25),
 (543, 0.25),
 (562, 0.25),
 (570, 0.25),
 (572, 0.25),
 (580, 0.25),
 (585, 0.25),
 (596, 0.25),
 (604, 0.25),
 (642, 0.25),
 (654, 0.25),
 (670, 0.25),
 (674, 0.25),
 (682, 0.25),
 (683, 0.25),
 (699, 0.25),
 (706, 0.25),
 (722, 0.25),
 (734, 0.25),
 (749, 0.25),
 (772, 0.25),
 (782, 0.25),
 (787, 0.25),
 (791, 0.25),
 (793, 0.25),
 (800, 0.25),
 (812, 0.25),
 (820, 0.25),
 (827, 0.25),
 (834, 0.25),
 (837, 0.25),
 (5, 0.22360679774997896),
 (14, 0.22360679774997896),
 (16, 0.22360679774997896),
 (30, 0.22360679774997896),
 (43, 0.22360679774997896),
 (77, 0.22360679774997896),
 (79, 0.22360679774997896),
 (92, 0.22360679774997896),
 (150, 0.22360679774997896),
 (152, 0.22360679774997896),
 (157, 0.22360679774997896),
 (159, 0.22360679774997896),
 (171, 0.22360679774997896),
 (209, 0.22360679774997896),
 (224, 0.22360679774997896),
 (263, 0.22360679774997896),
 (280, 0.22360679774997896),
 (296, 0.22360679774997896),
 (297, 0.22360679774997896),
 (308, 0.22360679774997896),
 (313, 0.22360679774997896),
 (314, 0.22360679774997896),
 (372, 0.22360679774997896),
 (376, 0.22360679774997896),
 (387, 0.22360679774997896),
 (388, 0.22360679774997896),
 (396, 0.22360679774997896),
 (397, 0.22360679774997896),
 (417, 0.22360679774997896),
 (422, 0.22360679774997896),
 (448, 0.22360679774997896),
 (491, 0.22360679774997896),
 (506, 0.22360679774997896),
 (530, 0.22360679774997896),
 (548, 0.22360679774997896),
 (560, 0.22360679774997896),
 (568, 0.22360679774997896),
 (578, 0.22360679774997896),
 (591, 0.22360679774997896),
 (598, 0.22360679774997896),
 (599, 0.22360679774997896),
 (625, 0.22360679774997896),
 (640, 0.22360679774997896),
 (649, 0.22360679774997896),
 (652, 0.22360679774997896),
 (665, 0.22360679774997896),
 (679, 0.22360679774997896),
 (696, 0.22360679774997896),
 (712, 0.22360679774997896),
 (714, 0.22360679774997896),
 (735, 0.22360679774997896),
 (736, 0.22360679774997896),
 (739, 0.22360679774997896),
 (755, 0.22360679774997896),
 (763, 0.22360679774997896),
 (774, 0.22360679774997896),
 (786, 0.22360679774997896),
 (796, 0.22360679774997896),
 (801, 0.22360679774997896),
 (802, 0.22360679774997896),
 (829, 0.22360679774997896),
 (832, 0.22360679774997896),
 (835, 0.22360679774997896),
 (844, 0.22360679774997896),
 (847, 0.22360679774997896),
 (21, 0.20412414523193154),
 (45, 0.20412414523193154),
 (66, 0.20412414523193154),
 (67, 0.20412414523193154),
 (84, 0.20412414523193154),
 (116, 0.20412414523193154),
 (118, 0.20412414523193154),
 (154, 0.20412414523193154),
 (176, 0.20412414523193154),
 (191, 0.20412414523193154),
 (211, 0.20412414523193154),
 (226, 0.20412414523193154),
 (239, 0.20412414523193154),
 (269, 0.20412414523193154),
 (298, 0.20412414523193154),
 (310, 0.20412414523193154),
 (356, 0.20412414523193154),
 (384, 0.20412414523193154),
 (393, 0.20412414523193154),
 (404, 0.20412414523193154),
 (456, 0.20412414523193154),
 (463, 0.20412414523193154),
 (505, 0.20412414523193154),
 (532, 0.20412414523193154),
 (600, 0.20412414523193154),
 (609, 0.20412414523193154),
 (614, 0.20412414523193154),
 (664, 0.20412414523193154),
 (730, 0.20412414523193154),
 (731, 0.20412414523193154),
 (732, 0.20412414523193154),
 (738, 0.20412414523193154),
 (750, 0.20412414523193154),
 (764, 0.20412414523193154),
 (767, 0.20412414523193154),
 (780, 0.20412414523193154),
 (17, 0.1889822365046136),
 (27, 0.1889822365046136),
 (28, 0.1889822365046136),
 (33, 0.1889822365046136),
 (48, 0.1889822365046136),
 (75, 0.1889822365046136),
 (85, 0.1889822365046136),
 (147, 0.1889822365046136),
 (315, 0.1889822365046136),
 (425, 0.1889822365046136),
 (429, 0.1889822365046136),
 (444, 0.1889822365046136),
 (449, 0.1889822365046136),
 (460, 0.1889822365046136),
 (493, 0.1889822365046136),
 (507, 0.1889822365046136),
 (534, 0.1889822365046136),
 (601, 0.1889822365046136),
 (630, 0.1889822365046136),
 (631, 0.1889822365046136),
 (638, 0.1889822365046136),
 (667, 0.1889822365046136),
 (668, 0.1889822365046136),
 (689, 0.1889822365046136),
 (724, 0.1889822365046136),
 (756, 0.1889822365046136),
 (760, 0.1889822365046136),
 (822, 0.1889822365046136),
 (823, 0.1889822365046136),
 (846, 0.1889822365046136),
 (322, 0.17677669529663687),
 (737, 0.17677669529663687),
 (0, 0.0),
 (3, 0.0),
 (7, 0.0),
 (10, 0.0),
 (18, 0.0),
 (25, 0.0),
 (26, 0.0),
 (31, 0.0),
 (34, 0.0),
 (38, 0.0),
 (40, 0.0),
 (41, 0.0),
 (46, 0.0),
 (47, 0.0),
 (49, 0.0),
 (50, 0.0),
 (52, 0.0),
 (53, 0.0),
 (54, 0.0),
 (56, 0.0),
 (57, 0.0),
 (59, 0.0),
 (60, 0.0),
 (62, 0.0),
 (68, 0.0),
 (69, 0.0),
 (71, 0.0),
 (73, 0.0),
 (80, 0.0),
 (81, 0.0),
 (83, 0.0),
 (88, 0.0),
 (89, 0.0),
 (91, 0.0),
 (93, 0.0),
 (96, 0.0),
 (97, 0.0),
 (99, 0.0),
 (102, 0.0),
 (103, 0.0),
 (107, 0.0),
 (108, 0.0),
 (109, 0.0),
 (110, 0.0),
 (111, 0.0),
 (114, 0.0),
 (123, 0.0),
 (126, 0.0),
 (128, 0.0),
 (129, 0.0),
 (130, 0.0),
 (131, 0.0),
 (134, 0.0),
 (142, 0.0),
 (144, 0.0),
 (149, 0.0),
 (155, 0.0),
 (156, 0.0),
 (158, 0.0),
 (160, 0.0),
 (161, 0.0),
 (164, 0.0),
 (167, 0.0),
 (168, 0.0),
 (169, 0.0),
 (172, 0.0),
 (174, 0.0),
 (180, 0.0),
 (181, 0.0),
 (186, 0.0),
 (187, 0.0),
 (189, 0.0),
 (190, 0.0),
 (192, 0.0),
 (196, 0.0),
 (197, 0.0),
 (199, 0.0),
 (201, 0.0),
 (204, 0.0),
 (208, 0.0),
 (210, 0.0),
 (213, 0.0),
 (215, 0.0),
 (217, 0.0),
 (218, 0.0),
 (219, 0.0),
 (220, 0.0),
 (223, 0.0),
 (225, 0.0),
 (228, 0.0),
 (229, 0.0),
 (233, 0.0),
 (235, 0.0),
 (236, 0.0),
 (238, 0.0),
 (240, 0.0),
 (242, 0.0),
 (243, 0.0),
 (244, 0.0),
 (245, 0.0),
 (246, 0.0),
 (247, 0.0),
 (248, 0.0),
 (250, 0.0),
 (256, 0.0),
 (258, 0.0),
 (259, 0.0),
 (262, 0.0),
 (264, 0.0),
 (265, 0.0),
 (267, 0.0),
 (270, 0.0),
 (276, 0.0),
 (277, 0.0),
 (278, 0.0),
 (282, 0.0),
 (283, 0.0),
 (284, 0.0),
 (285, 0.0),
 (287, 0.0),
 (289, 0.0),
 (291, 0.0),
 (299, 0.0),
 (300, 0.0),
 (309, 0.0),
 (311, 0.0),
 (312, 0.0),
 (317, 0.0),
 (319, 0.0),
 (320, 0.0),
 (321, 0.0),
 (323, 0.0),
 (325, 0.0),
 (326, 0.0),
 (327, 0.0),
 (328, 0.0),
 (329, 0.0),
 (330, 0.0),
 (334, 0.0),
 (335, 0.0),
 (337, 0.0),
 (338, 0.0),
 (341, 0.0),
 (347, 0.0),
 (348, 0.0),
 (354, 0.0),
 (362, 0.0),
 (365, 0.0),
 (368, 0.0),
 (369, 0.0),
 (370, 0.0),
 (373, 0.0),
 (375, 0.0),
 (382, 0.0),
 (383, 0.0),
 (392, 0.0),
 (401, 0.0),
 (403, 0.0),
 (405, 0.0),
 (406, 0.0),
 (407, 0.0),
 (409, 0.0),
 (410, 0.0),
 (411, 0.0),
 (413, 0.0),
 (414, 0.0),
 (415, 0.0),
 (418, 0.0),
 (424, 0.0),
 (426, 0.0),
 (427, 0.0),
 (428, 0.0),
 (434, 0.0),
 (435, 0.0),
 (436, 0.0),
 (437, 0.0),
 (438, 0.0),
 (442, 0.0),
 (450, 0.0),
 (451, 0.0),
 (452, 0.0),
 (453, 0.0),
 (459, 0.0),
 (462, 0.0),
 (466, 0.0),
 (467, 0.0),
 (469, 0.0),
 (470, 0.0),
 (473, 0.0),
 (477, 0.0),
 (484, 0.0),
 (485, 0.0),
 (487, 0.0),
 (488, 0.0),
 (489, 0.0),
 (490, 0.0),
 (492, 0.0),
 (497, 0.0),
 (498, 0.0),
 (500, 0.0),
 (501, 0.0),
 (502, 0.0),
 (503, 0.0),
 (504, 0.0),
 (511, 0.0),
 (512, 0.0),
 (514, 0.0),
 (516, 0.0),
 (517, 0.0),
 (518, 0.0),
 (520, 0.0),
 (522, 0.0),
 (525, 0.0),
 (527, 0.0),
 (528, 0.0),
 (529, 0.0),
 (531, 0.0),
 (533, 0.0),
 (536, 0.0),
 (537, 0.0),
 (539, 0.0),
 (540, 0.0),
 (541, 0.0),
 (542, 0.0),
 (547, 0.0),
 (549, 0.0),
 (552, 0.0),
 (553, 0.0),
 (556, 0.0),
 (558, 0.0),
 (559, 0.0),
 (563, 0.0),
 (564, 0.0),
 (565, 0.0),
 (567, 0.0),
 (571, 0.0),
 (575, 0.0),
 (583, 0.0),
 (589, 0.0),
 (590, 0.0),
 (595, 0.0),
 (597, 0.0),
 (602, 0.0),
 (608, 0.0),
 (610, 0.0),
 (613, 0.0),
 (617, 0.0),
 (618, 0.0),
 (619, 0.0),
 (621, 0.0),
 (624, 0.0),
 (627, 0.0),
 (632, 0.0),
 (633, 0.0),
 (635, 0.0),
 (636, 0.0),
 (646, 0.0),
 (647, 0.0),
 (648, 0.0),
 (650, 0.0),
 (651, 0.0),
 (653, 0.0),
 (656, 0.0),
 (669, 0.0),
 (671, 0.0),
 (672, 0.0),
 (673, 0.0),
 (675, 0.0),
 (676, 0.0),
 (677, 0.0),
 (678, 0.0),
 (681, 0.0),
 (685, 0.0),
 (686, 0.0),
 (688, 0.0),
 (693, 0.0),
 (694, 0.0),
 (701, 0.0),
 (702, 0.0),
 (707, 0.0),
 (710, 0.0),
 (711, 0.0),
 (713, 0.0),
 (715, 0.0),
 (716, 0.0),
 (718, 0.0),
 (725, 0.0),
 (726, 0.0),
 (727, 0.0),
 (729, 0.0),
 (733, 0.0),
 (742, 0.0),
 (744, 0.0),
 (746, 0.0),
 (747, 0.0),
 (751, 0.0),
 (757, 0.0),
 (758, 0.0),
 (761, 0.0),
 (762, 0.0),
 (766, 0.0),
 (768, 0.0),
 (771, 0.0),
 (773, 0.0),
 (776, 0.0),
 (778, 0.0),
 (781, 0.0),
 (783, 0.0),
 (790, 0.0),
 (792, 0.0),
 (794, 0.0),
 (797, 0.0),
 (799, 0.0),
 (806, 0.0),
 (807, 0.0),
 (813, 0.0),
 (816, 0.0),
 (817, 0.0),
 (819, 0.0),
 (824, 0.0),
 (825, 0.0),
 (826, 0.0),
 (828, 0.0),
 (833, 0.0),
 (836, 0.0),
 (839, 0.0),
 (840, 0.0),
 (842, 0.0),
 (848, 0.0),
 (849, 0.0)]

In [21]:
animesama = list(filter(lambda x:x[1]>0.7, animesama))
list(animesama)

[(6, 1.0),
 (74, 0.7559289460184544),
 (112, 1.0),
 (113, 0.75),
 (145, 1.0),
 (146, 1.0),
 (175, 0.75),
 (182, 0.8164965809277261),
 (202, 1.0),
 (206, 0.7559289460184544),
 (231, 0.7559289460184544),
 (241, 0.7559289460184544),
 (271, 0.8164965809277261),
 (304, 0.75),
 (339, 0.75),
 (352, 0.8164965809277261),
 (371, 0.75),
 (398, 0.8660254037844388),
 (513, 0.75),
 (515, 0.7559289460184544),
 (561, 0.75),
 (566, 0.7559289460184544),
 (579, 0.75),
 (588, 0.7559289460184544),
 (629, 0.75),
 (644, 0.7559289460184544),
 (680, 0.7071067811865475),
 (698, 0.8660254037844388),
 (753, 0.8164965809277261),
 (784, 0.8944271909999159),
 (821, 0.75)]

In [22]:
for i in animesama:
    print(df2.iloc[i[0]]['name'])

Hunter x Hunter (2011)
One Piece
Hunter x Hunter
Noragami Aragoto
Hunter x Hunter OVA
Hunter x Hunter: Greed Island Final
Katekyo Hitman Reborn!
Saint Seiya: The Lost Canvas - Meiou Shinwa 2
Hunter x Hunter: Greed Island
Dragon Ball Z
One Piece: Episode of Merry - Mou Hitori no Nakama no Monogatari
One Piece: Episode of Nami - Koukaishi no Namida to Nakama no Kizuna
Saint Seiya: The Lost Canvas - Meiou Shinwa
D.Gray-man
Noragami
One Piece Film: Strong World Episode 0
Ginga Nagareboshi Gin
Noragami Aragoto OVA
D.Gray-man Hallow
Dragon Ball Kai (2014)
Lupin III (2015)
Saint Seiya: Meiou Hades Meikai-hen
Shin Mazinger Shougeki! Z-hen
Dragon Ball Kai
Lupin III: Part II
Claymore
Michiko to Hatchin
Noragami OVA
One Piece: Episode of Luffy - Hand Island no Bouken
Naruto: Shippuuden Movie 6 - Road to Ninja
Saint Seiya: Meiou Hades Elysion-hen

In [23]:
ext2 = CountVectorizer(tokenizer = lambda x: x.split(', '))
mtype = ext.fit_transform(df2['type'])

In [24]:
mtype.toarray()

array([[1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
       ...,
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [25]:
mtype.shape

(850, 6)

In [26]:
cs2 = cosine_similarity(mtype)

In [27]:
animesama2 = list(enumerate(cs2[indexsuka]))

In [28]:
animesama2 = list(filter(lambda x:x[1]>0.7, animesama2))
list(animesama2)

[(1, 1.0),
 (2, 1.0),
 (3, 1.0),
 (4, 1.0),
 (5, 1.0),
 (6, 1.0),
 (9, 1.0),
 (10, 1.0),
 (12, 1.0),
 (13, 1.0),
 (14, 1.0),
 (16, 1.0),
 (17, 1.0),
 (19, 1.0),
 (20, 1.0),
 (22, 1.0),
 (23, 1.0),
 (26, 1.0),
 (27, 1.0),
 (28, 1.0),
 (29, 1.0),
 (30, 1.0),
 (31, 1.0),
 (32, 1.0),
 (34, 1.0),
 (36, 1.0),
 (38, 1.0),
 (39, 1.0),
 (40, 1.0),
 (42, 1.0),
 (43, 1.0),
 (44, 1.0),
 (46, 1.0),
 (47, 1.0),
 (49, 1.0),
 (50, 1.0),
 (51, 1.0),
 (53, 1.0),
 (54, 1.0),
 (56, 1.0),
 (57, 1.0),
 (58, 1.0),
 (61, 1.0),
 (62, 1.0),
 (64, 1.0),
 (67, 1.0),
 (68, 1.0),
 (69, 1.0),
 (72, 1.0),
 (73, 1.0),
 (74, 1.0),
 (75, 1.0),
 (76, 1.0),
 (78, 1.0),
 (79, 1.0),
 (80, 1.0),
 (82, 1.0),
 (83, 1.0),
 (84, 1.0),
 (86, 1.0),
 (87, 1.0),
 (88, 1.0),
 (91, 1.0),
 (93, 1.0),
 (94, 1.0),
 (95, 1.0),
 (96, 1.0),
 (97, 1.0),
 (98, 1.0),
 (99, 1.0),
 (100, 1.0),
 (101, 1.0),
 (104, 1.0),
 (105, 1.0),
 (106, 1.0),
 (108, 1.0),
 (109, 1.0),
 (110, 1.0),
 (111, 1.0),
 (112, 1.0),
 (113, 1.0),
 (114, 1.0),
 (116, 1.0),
 (118, 1.0),
 (119, 1.0),
 (120, 1.0),
 (121, 1.0),
 (122, 1.0),
 (123, 1.0),
 (124, 1.0),
 (127, 1.0),
 (128, 1.0),
 (131, 1.0),
 (134, 1.0),
 (135, 1.0),
 (138, 1.0),
 (139, 1.0),
 (141, 1.0),
 (142, 1.0),
 (144, 1.0),
 (148, 1.0),
 (149, 1.0),
 (150, 1.0),
 (151, 1.0),
 (153, 1.0),
 (156, 1.0),
 (157, 1.0),
 (158, 1.0),
 (159, 1.0),
 (160, 1.0),
 (161, 1.0),
 (164, 1.0),
 (166, 1.0),
 (167, 1.0),
 (168, 1.0),
 (172, 1.0),
 (173, 1.0),
 (175, 1.0),
 (176, 1.0),
 (177, 1.0),
 (178, 1.0),
 (179, 1.0),
 (180, 1.0),
 (183, 1.0),
 (184, 1.0),
 (185, 1.0),
 (188, 1.0),
 (197, 1.0),
 (199, 1.0),
 (200, 1.0),
 (201, 1.0),
 (204, 1.0),
 (206, 1.0),
 (210, 1.0),
 (211, 1.0),
 (214, 1.0),
 (218, 1.0),
 (219, 1.0),
 (221, 1.0),
 (222, 1.0),
 (223, 1.0),
 (224, 1.0),
 (228, 1.0),
 (229, 1.0),
 (230, 1.0),
 (232, 1.0),
 (235, 1.0),
 (236, 1.0),
 (237, 1.0),
 (238, 1.0),
 (240, 1.0),
 (242, 1.0),
 (243, 1.0),
 (248, 1.0),
 (250, 1.0),
 (251, 1.0),
 (252, 1.0),
 (254, 1.0),
 (255, 1.0),
 (256, 1.0),
 (257, 1.0),
 (258, 1.0),
 (259, 1.0),
 (260, 1.0),
 (262, 1.0),
 (263, 1.0),
 (264, 1.0),
 (266, 1.0),
 (267, 1.0),
 (268, 1.0),
 (269, 1.0),
 (270, 1.0),
 (272, 1.0),
 (273, 1.0),
 (275, 1.0),
 (277, 1.0),
 (278, 1.0),
 (280, 1.0),
 (281, 1.0),
 (282, 1.0),
 (284, 1.0),
 (287, 1.0),
 (288, 1.0),
 (290, 1.0),
 (291, 1.0),
 (295, 1.0),
 (298, 1.0),
 (299, 1.0),
 (300, 1.0),
 (301, 1.0),
 (303, 1.0),
 (304, 1.0),
 (308, 1.0),
 (309, 1.0),
 (310, 1.0),
 (313, 1.0),
 (314, 1.0),
 (318, 1.0),
 (319, 1.0),
 (321, 1.0),
 (322, 1.0),
 (323, 1.0),
 (324, 1.0),
 (325, 1.0),
 (326, 1.0),
 (330, 1.0),
 (331, 1.0),
 (334, 1.0),
 (335, 1.0),
 (337, 1.0),
 (338, 1.0),
 (339, 1.0),
 (342, 1.0),
 (346, 1.0),
 (347, 1.0),
 (348, 1.0),
 (349, 1.0),
 (351, 1.0),
 (353, 1.0),
 (355, 1.0),
 (356, 1.0),
 (357, 1.0),
 (360, 1.0),
 (364, 1.0),
 (367, 1.0),
 (368, 1.0),
 (369, 1.0),
 (371, 1.0),
 (372, 1.0),
 (373, 1.0),
 (374, 1.0),
 (376, 1.0),
 (381, 1.0),
 (382, 1.0),
 (386, 1.0),
 (388, 1.0),
 (390, 1.0),
 (391, 1.0),
 (392, 1.0),
 (395, 1.0),
 (396, 1.0),
 (397, 1.0),
 (400, 1.0),
 (401, 1.0),
 (403, 1.0),
 (404, 1.0),
 (405, 1.0),
 (406, 1.0),
 (410, 1.0),
 (414, 1.0),
 (416, 1.0),
 (418, 1.0),
 (427, 1.0),
 (428, 1.0),
 (433, 1.0),
 (434, 1.0),
 (435, 1.0),
 (436, 1.0),
 (437, 1.0),
 (438, 1.0),
 (440, 1.0),
 (442, 1.0),
 (444, 1.0),
 (445, 1.0),
 (447, 1.0),
 (448, 1.0),
 (449, 1.0),
 (451, 1.0),
 (452, 1.0),
 (457, 1.0),
 (458, 1.0),
 (459, 1.0),
 (462, 1.0),
 (463, 1.0),
 (464, 1.0),
 (466, 1.0),
 (470, 1.0),
 (473, 1.0),
 (475, 1.0),
 (476, 1.0),
 (479, 1.0),
 (481, 1.0),
 (482, 1.0),
 (483, 1.0),
 (485, 1.0),
 (488, 1.0),
 (489, 1.0),
 (490, 1.0),
 (491, 1.0),
 (492, 1.0),
 (493, 1.0),
 (494, 1.0),
 (495, 1.0),
 (497, 1.0),
 (498, 1.0),
 (499, 1.0),
 (500, 1.0),
 (502, 1.0),
 (503, 1.0),
 (507, 1.0),
 (509, 1.0),
 (511, 1.0),
 (513, 1.0),
 (515, 1.0),
 (516, 1.0),
 (517, 1.0),
 (518, 1.0),
 (520, 1.0),
 (522, 1.0),
 (523, 1.0),
 (534, 1.0),
 (537, 1.0),
 (538, 1.0),
 (539, 1.0),
 (540, 1.0),
 (541, 1.0),
 (543, 1.0),
 (546, 1.0),
 (551, 1.0),
 (552, 1.0),
 (553, 1.0),
 (554, 1.0),
 (555, 1.0),
 (556, 1.0),
 (557, 1.0),
 (558, 1.0),
 (560, 1.0),
 (561, 1.0),
 (563, 1.0),
 (564, 1.0),
 (568, 1.0),
 (571, 1.0),
 (572, 1.0),
 (576, 1.0),
 (577, 1.0),
 (578, 1.0),
 (579, 1.0),
 (580, 1.0),
 (581, 1.0),
 (582, 1.0),
 (583, 1.0),
 (584, 1.0),
 (585, 1.0),
 (588, 1.0),
 (591, 1.0),
 (592, 1.0),
 (593, 1.0),
 (594, 1.0),
 (595, 1.0),
 (597, 1.0),
 (598, 1.0),
 (599, 1.0),
 (600, 1.0),
 (608, 1.0),
 (612, 1.0),
 (615, 1.0),
 (617, 1.0),
 (619, 1.0),
 (620, 1.0),
 (621, 1.0),
 (622, 1.0),
 (628, 1.0),
 (629, 1.0),
 (631, 1.0),
 (633, 1.0),
 (635, 1.0),
 (637, 1.0),
 (641, 1.0),
 (643, 1.0),
 (644, 1.0),
 (647, 1.0),
 (649, 1.0),
 (650, 1.0),
 (655, 1.0),
 (658, 1.0),
 (659, 1.0),
 (660, 1.0),
 (665, 1.0),
 (666, 1.0),
 (668, 1.0),
 (669, 1.0),
 (671, 1.0),
 (672, 1.0),
 (674, 1.0),
 (675, 1.0),
 (676, 1.0),
 (677, 1.0),
 (679, 1.0),
 (680, 1.0),
 (683, 1.0),
 (684, 1.0),
 (685, 1.0),
 (686, 1.0),
 (687, 1.0),
 (689, 1.0),
 (690, 1.0),
 (696, 1.0),
 (701, 1.0),
 (702, 1.0),
 (705, 1.0),
 (706, 1.0),
 (708, 1.0),
 (712, 1.0),
 (713, 1.0),
 (715, 1.0),
 (720, 1.0),
 (722, 1.0),
 (723, 1.0),
 (724, 1.0),
 (727, 1.0),
 (729, 1.0),
 (730, 1.0),
 (733, 1.0),
 (735, 1.0),
 (736, 1.0),
 (738, 1.0),
 (739, 1.0),
 (740, 1.0),
 (741, 1.0),
 (742, 1.0),
 (744, 1.0),
 (746, 1.0),
 (755, 1.0),
 (756, 1.0),
 (757, 1.0),
 (758, 1.0),
 (760, 1.0),
 (762, 1.0),
 (764, 1.0),
 (766, 1.0),
 (768, 1.0),
 (771, 1.0),
 (775, 1.0),
 (776, 1.0),
 (781, 1.0),
 (785, 1.0),
 (787, 1.0),
 (788, 1.0),
 (789, 1.0),
 (790, 1.0),
 (793, 1.0),
 (794, 1.0),
 (795, 1.0),
 (802, 1.0),
 (803, 1.0),
 (804, 1.0),
 (805, 1.0),
 (806, 1.0),
 (807, 1.0),
 (812, 1.0),
 (814, 1.0),
 (816, 1.0),
 (819, 1.0),
 (822, 1.0),
 (824, 1.0),
 (825, 1.0),
 (826, 1.0),
 (828, 1.0),
 (829, 1.0),
 (830, 1.0),
 (832, 1.0),
 (833, 1.0),
 (838, 1.0),
 (839, 1.0),
 (841, 1.0),
 (842, 1.0),
 (846, 1.0),
 (847, 1.0),
 (849, 1.0)]

In [29]:
for i in animesama2[:5]:
    print(df2.iloc[i[0]]['name'])

Fullmetal Alchemist: Brotherhood
Gintama°
Steins;Gate
Gintama&#039;
Haikyuu!!: Karasuno Koukou VS Shiratorizawa Gakuen Koukou

In [30]:
m3 = CountVectorizer().fit_transform(df2['genre'], df2['type'])

In [31]:
cs3 = cosine_similarity(m3)

In [32]:
animesama3 = list(enumerate(cs3[indexsuka]))

In [33]:
animesama3 = list(filter(lambda x:x[1]>0.7, animesama3))
list(animesama3)

[(6, 0.9999999999999999),
 (74, 0.7905694150420948),
 (86, 0.7302967433402215),
 (112, 0.9999999999999999),
 (145, 0.9999999999999999),
 (146, 0.9999999999999999),
 (175, 0.7999999999999999),
 (178, 0.7302967433402215),
 (182, 0.7905694150420948),
 (202, 0.9999999999999999),
 (206, 0.7453559924999298),
 (231, 0.7905694150420948),
 (241, 0.7905694150420948),
 (271, 0.7905694150420948),
 (352, 0.8451542547285165),
 (398, 0.7745966692414834),
 (513, 0.7999999999999999),
 (515, 0.7453559924999298),
 (566, 0.7453559924999298),
 (579, 0.7999999999999999),
 (582, 0.7302967433402215),
 (588, 0.7453559924999298),
 (644, 0.7905694150420948),
 (698, 0.7745966692414834),
 (717, 0.7302967433402215),
 (753, 0.8451542547285165),
 (784, 0.8451542547285165),
 (821, 0.7999999999999999)]

In [34]:
animesamasortir = sorted(animesama3, key = lambda x:x[1], reverse = True)
animesamasortir

[(6, 0.9999999999999999),
 (112, 0.9999999999999999),
 (145, 0.9999999999999999),
 (146, 0.9999999999999999),
 (202, 0.9999999999999999),
 (352, 0.8451542547285165),
 (753, 0.8451542547285165),
 (784, 0.8451542547285165),
 (175, 0.7999999999999999),
 (513, 0.7999999999999999),
 (579, 0.7999999999999999),
 (821, 0.7999999999999999),
 (74, 0.7905694150420948),
 (182, 0.7905694150420948),
 (231, 0.7905694150420948),
 (241, 0.7905694150420948),
 (271, 0.7905694150420948),
 (644, 0.7905694150420948),
 (398, 0.7745966692414834),
 (698, 0.7745966692414834),
 (206, 0.7453559924999298),
 (515, 0.7453559924999298),
 (566, 0.7453559924999298),
 (588, 0.7453559924999298),
 (86, 0.7302967433402215),
 (178, 0.7302967433402215),
 (582, 0.7302967433402215),
 (717, 0.7302967433402215)]

In [35]:
for i in animesama3:
    print(df2.iloc[i[0]]['name'])

Hunter x Hunter (2011)
One Piece
Shingeki no Kyojin
Hunter x Hunter
Hunter x Hunter OVA
Hunter x Hunter: Greed Island Final
Katekyo Hitman Reborn!
Boku no Hero Academia
Saint Seiya: The Lost Canvas - Meiou Shinwa 2
Hunter x Hunter: Greed Island
Dragon Ball Z
One Piece: Episode of Merry - Mou Hitori no Nakama no Monogatari
One Piece: Episode of Nami - Koukaishi no Namida to Nakama no Kizuna
Saint Seiya: The Lost Canvas - Meiou Shinwa
One Piece Film: Strong World Episode 0
Noragami Aragoto OVA
D.Gray-man Hallow
Dragon Ball Kai (2014)
Saint Seiya: Meiou Hades Meikai-hen
Shin Mazinger Shougeki! Z-hen
Bleach
Dragon Ball Kai
Claymore
Noragami OVA
Shingeki no Kyojin OVA
One Piece: Episode of Luffy - Hand Island no Bouken
Naruto: Shippuuden Movie 6 - Road to Ninja
Saint Seiya: Meiou Hades Elysion-hen

# Collaborative Filtering

In [36]:
rating = pd.read_csv('~/Downloads/rating.csv')
rating.head()

   user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1

In [39]:
data = pd.merge(df2, rating, on = 'anime_id')
data.head()

,anime_id,name,genre,type,episodes,rating_x,members,user_id,rating_y
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,99,5
1,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,152,10
2,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,244,10
3,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,271,10
4,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,278,-1

In [41]:
mat = data.pivot_table(index = 'user_id', columns = 'name', values = 'rating_y')
mat.head()

name,91 Days,AKB0048: Next Stage,Ajin Part 1: Shoudou,Akachan to Boku,Akagami no Shirayuki-hime,Akagami no Shirayuki-hime 2nd Season,Akame ga Kill!,Akatsuki no Yona,Akira,Angel Beats!,...,Zetsuen no Tempest,Zoku Natsume Yuujinchou,Zoku Sayonara Zetsubou Sensei,ef: A Tale of Melodies.,ef: A Tale of Memories.,xxxHOLiC,xxxHOLiC Kei,xxxHOLiC Movie: Manatsu no Yoru no Yume,xxxHOLiC Rou,xxxHOLiC Shunmuki
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,-1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,8.0,3.0,...,NaN,NaN,7.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN

In [74]:
kimi_rating = mat['Naruto']
kimi_rating

user_id
1       -1.0
2        NaN
3        8.0
4        NaN
5        6.0
        ...
73512    NaN
73513    NaN
73514    NaN
73515    NaN
73516    NaN
Name: Naruto, Length: 72052, dtype: float64

In [75]:
similar_kimi = mat.corrwith(kimi_rating)

/Users/muhammadramzy/opt/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py:2526: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)
/Users/muhammadramzy/opt/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py:2455: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)

In [76]:
corr_kimi = pd.DataFrame(similar_kimi, columns = ['Correlation'])
corr_kimi.dropna(inplace = True)
corr_kimi.head(20)

                                                    Correlation
name
91 Days                                                0.499982
AKB0048: Next Stage                                    0.593548
Ajin Part 1: Shoudou                                   0.451589
Akachan to Boku                                        0.519318
Akagami no Shirayuki-hime                              0.506684
Akagami no Shirayuki-hime 2nd Season                   0.500054
Akame ga Kill!                                         0.590885
Akatsuki no Yona                                       0.560429
Akira                                                  0.569814
Angel Beats!                                           0.602401
Ano Hi Mita Hana no Namae wo Bokutachi wa Mada ...     0.593145
Ano Hi Mita Hana no Namae wo Bokutachi wa Mada ...     0.603308
Another                                                0.605638
Ansatsu Kyoushitsu (TV)                                0.596458
Ansatsu Kyoushitsu (TV) 2nd Season                     0.559351
Ansatsu Kyoushitsu (TV) 2nd Season: Kagaijugyou...     0.610603
Ao Haru Ride                                           0.572547
Ao no Exorcist                                         0.662509
Ao no Exorcist Movie                                   0.607196
Aoi Bungaku Series                                     0.572942

In [77]:
data['ratings count'] = pd.DataFrame(data.groupby('name')['rating_y'].count())

In [78]:
data

,anime_id,name,genre,type,episodes,rating_x,members,user_id,rating_y,ratings count
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,99,5,NaN
1,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,152,10,NaN
2,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,244,10,NaN
3,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,271,10,NaN
4,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,278,-1,NaN
...,...,...,...,...,...,...,...,...,...,...
3337693,120,Fruits Basket,"Comedy, Drama, Fantasy, Romance, Shoujo, Slice...",TV,26,7.80,242553,73490,10,NaN
3337694,120,Fruits Basket,"Comedy, Drama, Fantasy, Romance, Shoujo, Slice...",TV,26,7.80,242553,73491,10,NaN
3337695,120,Fruits Basket,"Comedy, Drama, Fantasy, Romance, Shoujo, Slice...",TV,26,7.80,242553,73495,7,NaN
3337696,120,Fruits Basket,"Comedy, Drama, Fantasy, Romance, Shoujo, Slice...",TV,26,7.80,242553,73500,9,NaN
3337697,120,Fruits Basket,"Comedy, Drama, Fantasy, Romance, Shoujo, Slice...",TV,26,7.80,242553,73512,5,NaN

In [79]:
data.groupby('name')['rating_y'].count().sort_values(ascending = False).head()

name
Death Note                         39340
Sword Art Online                   30583
Shingeki no Kyojin                 29584
Code Geass: Hangyaku no Lelouch    27718
Elfen Lied                         27506
Name: rating_y, dtype: int64

In [80]:
data.groupby('name')['rating_y'].count()

name
91 Days                                    1825
AKB0048: Next Stage                         876
Ajin Part 1: Shoudou                        375
Akachan to Boku                             249
Akagami no Shirayuki-hime                  3305
                                           ...
xxxHOLiC                                   5475
xxxHOLiC Kei                               3413
xxxHOLiC Movie: Manatsu no Yoru no Yume    2365
xxxHOLiC Rou                               1513
xxxHOLiC Shunmuki                          1974
Name: rating_y, Length: 832, dtype: int64

In [81]:
ratings = pd.DataFrame(data.groupby('name')['rating_y'].mean())
ratings['ratings count'] = pd.DataFrame(data.groupby('name')['rating_y'].count())
ratings

                                         rating_y  ratings count
name
91 Days                                  6.593973           1825
AKB0048: Next Stage                      6.205479            876
Ajin Part 1: Shoudou                     5.984000            375
Akachan to Boku                          6.212851            249
Akagami no Shirayuki-hime                6.312557           3305
...                                           ...            ...
xxxHOLiC                                 6.592146           5475
xxxHOLiC Kei                             6.720774           3413
xxxHOLiC Movie: Manatsu no Yoru no Yume  6.313742           2365
xxxHOLiC Rou                             6.403173           1513
xxxHOLiC Shunmuki                        6.238602           1974

[832 rows x 2 columns]

In [82]:
corr_kimi['ratings count'] = ratings['ratings count']
corr_kimi[corr_kimi['ratings count'] > 1500].sort_values('Correlation', ascending = False).head(20)

                                             Correlation  ratings count
name
Naruto                                          1.000000          25925
Bleach                                          0.720531          12845
InuYasha                                        0.704638           9328
Shaman King                                     0.696407           7814
Katekyo Hitman Reborn!                          0.694202           6739
The Law of Ueki                                 0.693139           2186
Rurouni Kenshin: Meiji Kenkaku Romantan         0.690855           7900
Romeo x Juliet                                  0.690726           3187
Shijou Saikyou no Deshi Kenichi                 0.690250           5654
Slayers                                         0.688689           3395
Sora no Otoshimono: Tokeijikake no Angeloid     0.687563           3161
Goku Sayonara Zetsubou Sensei                   0.684652           1812
Kyou kara Maou!                                 0.684535           1670
Soul Eater                                      0.683672          19759
Eyeshield 21                                    0.681721           2424
Yuu☆Yuu☆Hakusho                                 0.680854           6764
Dragon Ball                                     0.680600          14117
Fairy Tail                                      0.679945          12344
Saint Seiya                                     0.679541           2846
Initial D First Stage                           0.678373           2699